[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.3"
clap = { version = "4.5.4", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
nutype = "0.4.2"
regex = "1.10.4"
